version: "3.8"

services:
  ai:
    build:
      context: ./
      dockerfile: Dockerfile
      cache_from:
        - ai:latest
    env_file:
      - .env
    environment:
      BACKEND: localhost
      BACKEND_PORT: 5000
    # depends_on:
    #   backend:
    #     condition: service_started
    restart: unless-stopped
    ports:
      - "5050:5050"
